name: Go

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
#  branches: 
#    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
env:
  UPLOAD_BIN_FILE: true

jobs:

  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
        arch: [amd64]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        GOARCH: ${{ matrix.arch }}
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build ${{ matrix.platform }} ${{ matrix.arch }}
      if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
      id: test_run
      run: |
          ${GOROOT}/bin/go mod tidy
          
          echo "build"
          ${GOROOT}/bin/go build -o panas main.go
          
          echo "test"
          ./panas
          
